# Generated by Django 2.0.2 on 2018-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('city_as', models.CharField(max_length=32, verbose_name='ASCII City Name')),
                ('city_name', models.CharField(max_length=32, verbose_name='City name')),
                ('region', models.CharField(max_length=32, verbose_name='Region')),
                ('population', models.CharField(max_length=32, verbose_name='Population')),
                ('latitude', models.CharField(max_length=32, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=32, verbose_name='Longitude')),
            ],
        ),
    ]
