# Generated by Django 2.0.2 on 2018-03-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(max_length=32, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(max_length=32, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(verbose_name='Population'),
        ),
    ]
